kind: Log
apiVersion: api.webmethods.io/beta
metadata:
  name: Petstore logging
  namespace: petstore
  version: '1.0'
  tags:
    - logging
spec:
  logRequestHeaders: true
  logRequestPayload: true
  logResponsePayload: true
  logResponseHeaders: true
  logGenerationFrequency: always
  destination:
    - email:
        - dhivakar.asokan@ibm.com
    - api_gateway
    - dev_portals
