kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: Sanity
  namespace: petstore
  version: '1.0'
  tags: []
spec:
  api:
    $ref: petstore:Petstore:1.0
  environment:
    $ref: petstore:Petstore environment:1.0
  request:
    - method: GET
      resource: /pet/${id}
      headers:
        - key: Content-Type
          value: application/json
      auth:
        noauth: true
      assertions:
        $ref: library:Library-BasicAssertion:1.0
