kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: ControlPlaneSanity
  version: 1.0
  namespace: cp
  tags:
    - demo
spec:
  api:
    $endpoint: https://devrealm3.apicp-aw-us.webmethods-dev.io
  environment:
    $ref: cp:ControlPlaneEnvironment:1.0

  request:
    - method: GET
      resource: /api/info
      headers:
        - key: Content-Type
          value: ${content-type}
        - key: Accept
          value: ${accept}
      
      auth:
        noauth: true
      settings:
        sslVerification: false
        encodeURL: true
      assertions:
        $ref: cp:ControlPlaneAssertions:1.0
    - method: GET
      resource: Untitled resource
      headers:
        - key: Content-Type
          value: application/json
      auth:
        noauth: true
