kind: PolicySeq
apiVersion: api.webmethods.io/daso
metadata:
  name: policyseq
  version: alpha
  namespace: daso
  tags:
    - seq
spec:
  transport:
    - $ref: daso:transport:alpha
  routing:
    - $ref: daso:routing:alpha
