kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: policyseq
  version: alpha
  namespace: daso
  tags:
    - seq
spec:
  transport:
    - $ref: daso:transport:alpha
  iam:
    - $ref: daso:My_IAM:alpha
  monitoring:
    - $ref: daso:log_invocation:alpha
  routing:
    - $ref: daso:routing:alpha
  req-processing:
    - $ref: daso:validate_API_Specification_policy:alpha

