kind: assertion
apiVersion: api.webmethods.io/beta
metadata:
  name: assertion
  version: alpha
  namespace: daso
  tags:
    - payEnv
spec:
  - name: "Validate the response status"
    key: "responseCode"
    value: 200
    action: "equals" 
  - name: "Less Than the response Time"
    key: "responseTime"
    value: 1000
    action: "lessThan"