kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: ServiceManagementTest
  version: alpha
  tags:
    - functional
  namespace: daso
spec:
  api:
   $ref: daso:ServiceManagement:alpha
   endpoint: "${hostname}/rest/apigateway/"
  environment:
   $ref: daso:environment:alpha
  request:
    - method: GET
      resource: apis
      headers:
        - key: Content-Type
          value: ${content-type}
        - key: Accept
          value: ${accept}
        - key: Authorization
          value: "Basic QWRtaW5pc3RyYXRvcjptYW5hZ2U="
      auth:
        basicAuth: true
      settings:
        sslVerification: false
        encodeURL: true
      assertions:
         $ref: daso:assertion:alpha

