kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: API Gateway Health Check
  version: "1.0"
  namespace: daso
  tags:
    - demo
spec:
  api:
    $endpoint: http://daso.dev.fyre.ibm.com:5555/rest/apigateway
  environment:
    $ref: cp:ControlPlaneEnvironment:1.0

  request:
    - method: GET
      resource: /health/engine
      headers:
        - key: Content-Type
          value: ${content-type}
        - key: Accept
          value: ${accept}

      auth:
        noauth: true
      settings:
        sslVerification: false
        encodeURL: true
      assertions:
        $ref: global:default-assertions:1.0
    - method: GET
      resource: Untitled resource
      headers:
        - key: Content-Type
          value: application/json
      auth:
        noauth: true
