name: API Studio CI Pipeline

on:

  pull_request:
    branches: [ "main" ]
    types:
      - opened
  
  workflow_dispatch:

jobs:
   Build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Projects checkout
        uses: actions/checkout@v4

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: CLI installation
        run: |
          npm install -g @apistudio/apim-cli

      - name: Build project
        run: |
          wm apim build -l ./ -o buildarchive.zip "Project Hydra"
        
   Test:
    name: Test APIs
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Check out projects
        uses: actions/checkout@v4

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          
      - name: CLI installation
        run: |
          npm install -g @apistudio/apim-cli
          
      - name: Run tests on the API Studio project
        run: |
         wm apim test -l ./ --deploy --target ${{ secrets.Gateway_URL }} --username ${{ secrets.Gateway_Username }} --password ${{ secrets.Gateway_Password }} --debug "Project Hydra"

   Performance:
    name: Run performance tests
    runs-on: self-hosted
    needs: [Build]
    steps:
      - name: Check out projects
        uses: actions/checkout@v4

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: ./"Project Hydra"/tests /performance/Loadtest.js
          flags: --out json=results.json

   Deploy:
    name: Deploy API Studio project
    runs-on: ubuntu-latest
    needs: [Build, Test,Performance]
    if: success()
    steps:
      - name: Check out projects
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: CLI installation
        run: |
          npm install -g @apistudio/apim-cli
          
      - name: Deploy API Studio project
        run: |
          wm apim deploy -l ./ --target ${{ secrets.Prod_Gateway_URL }} --username ${{ secrets.Prod_Gateway_Username }} --password ${{ secrets.Prod_Gateway_Password }} --overwrite --debug "Project Hydra"
