# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Projects checkout
        uses: actions/checkout@v4

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: CLI installation
        run: |
          npm install -g @apistudio/apim-cli

      # tmp solution for wm path
      - name: Build API Studio project
        run: |
          wm apim build -l ./ -o Aadhira.zip -d Aadhira
